apiVersion: v1
kind: Service
metadata:
  name: wp-mysql-service
  labels: 
    app: mysql-service
  namespace: wordpress
spec:
  type: ClusterIP
  selector:
    app: mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
