apiVersion: v1
kind: Service
metadata:
  name: wp-wordpress-service
  labels: 
    app: wordpress-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
